workflow:  
  - install
  - sail:parallel:
    - formatting
    - lint
  - build

tasks:
  install: &base
    image: node:12
    command:
      - npm
    args:
      - i
      - --ci
     
  formatting:
    <<: *base
    args:
      - run
      - prettier-check
      
  lint:
    <<: *base
    args:
      - run
      - lint

  build:
    <<: *base
    args:
      - run
      - build