version: "3"
services:
  cosmos:
    image: alekzonder/puppeteer:latest
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: /bin/sh -c
    command:
      - yarn --frozen-lockfile && yarn cosmos
  regression:
    image: alekzonder/puppeteer:latest
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: ["/bin/bash", "-c"]
    command:
      - npx wait-on http://cosmos:5000 && yarn run visual-regression-exec
    depends_on:
      - cosmos

volumes:
  node_modules:
