version: "3"
services:
  # Cosmos for visual regression
  cosmos-regression:
    image: alekzonder/puppeteer:latest
    user: root
    working_dir: /app
    volumes:
      - .:/app
      - node_modules_regression:/app/node_modules
    entrypoint: /bin/sh -c
    command:
      - yarn --frozen-lockfile && yarn cosmos

  # Visual regression
  regression:
    image: alekzonder/puppeteer:latest
    user: root
    working_dir: /app
    volumes:
      - .:/app
      - node_modules_regression:/app/node_modules
    environment:
      - TARGET_HOST=cosmos:5000
      - USER=root
    entrypoint: ["/bin/bash", "-c"]
    command:
      - npx wait-on http://cosmos:5000 && yarn jest --clearCache && yarn run visual-regression-exec
    depends_on:
      - cosmos-regression

  cosmos:
    image: node:14-alpine
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    entrypoint: ["/bin/sh", "-c"]
    command:
      - yarn && yarn cosmos

volumes:
  node_modules:
  node_modules_regression:
