jobs:
  install:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: |
            npm ci
            npm run postinstall # Required for @types/styled-components dependency issues
      - save_cache:
          key: node-cache-{{ .Revision }}
          paths:
            - "node_modules"

  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Revision }}
      - run: npm run lint

  prettier:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Revision }}
      - run: npm run prettier-check

  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Revision }}
      - run: npm run build
      - save_cache:
          key: build-cache-{{ .BuildNum }}
          paths:
            - "dist"

  deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .BuildNum }}
      - run:
          command: |
            node -e "process.env.CIRCLE_TAG === \`v\${require('./package.json').version}\` ? process.exit(0) : (console.error('Tag version does not line up with version in package.json') || process.exit(1))"
            npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - prettier:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - install
            - lint
            - prettier
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
