vars:
  - &deps
    restore_cache:
      keys:
        - node-cache-{{ checksum "package-lock.json" }}

jobs:
  install:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm run lint

  prettier:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm run prettier-check

  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm run build || exit 0 # Delete this once types are fixed
      - save_cache:
          key: build-cache-{{ .BuildNum }}
          paths:
            - "dist"

  deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          command: |
            echo "$CIRCLE_TAG"
            node -e "process.env.CIRCLE_TAG === `v${require(\'./package.json\').version}` || process.exit(1)"

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            # tags:
            #   only: /^v.*/
      - lint:
          requires:
            - install
      - prettier:
          requires:
            - install
      - build:
          requires:
            - install
          filters:
            # tags:
            #   only: /^v.*/
      - deploy:
          # requires:
          #   - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
